// vue/src/components/modal/Modal.tsx
import { definePropType } from '../../utils/index.ts'
import { ExtractPublicPropTypes, defineComponent } from 'vue'
import cn from 'classnames'
import { modalEmitters, ModalHeader } from './modules/ModalHeader'
import * as modalHeaderStylingProps from './modules/ModalHeader/stylingProps.ts'
import * as modalBodyStylingProps from './modules/ModalBody/stylingProps.ts'
import {
  modalBackdropStyle,
  modalWindowStyle
} from '@shared/components/modal/styles.css.ts'
import { ModalBody } from './modules/ModalBody'


const modalStylingProps = {
  backdropStyle: {
    type: definePropType<string>(String),
    default: modalBackdropStyle
  },
  windowStyle: {
    type: definePropType<string>(String),
    default: modalWindowStyle
  },
}

export const modalProps = {
  title: {
    type: definePropType<string>(String),
    default: ''
  },
  content: {
    type: definePropType<string>(String),
    default: ''
  },
  isCloseByBackdropClick: {
    type: definePropType<boolean>(Boolean),
    default: true
  },
  zIndex: {
    type: definePropType<number>(Number),
    default: 1
  },
  ...modalStylingProps,
  ...modalHeaderStylingProps,
  ...modalBodyStylingProps
} as const

export type ModalProps = ExtractPublicPropTypes<typeof modalProps>



export const Modal = defineComponent({
  props: modalProps,
  emits: modalEmitters,
  setup(props, { slots, attrs, emit }) {
    return () => (
      <>
        <div
          class={cn({[props.backdropStyle]: props.backdropStyle})}
          style={`z-index: ${props.zIndex}`}
          onClick={
            props.isCloseByBackdropClick
              ? () => emit('close')
              : undefined
          }
        ></div>
        <div
          {...attrs}
          class={cn({[props.windowStyle]: props.windowStyle})}
          style={`z-index: ${props.zIndex}`}
        >
          {slots.default
            ? slots.default(
                { onClose: () => emit('close') }
              )
            : <>
                {slots.header
                  ? slots.header(
                      { onClose: () => emit('close') }
                    )
                  : <ModalHeader
                      title={props.title}
                      style={props.headerStyle}
                      titleStyle={props.headerTitleStyle}
                      buttonStyle={props.headerButtonStyle}
                      buttonSize={props.headerButtonSize}
                      buttonVariant={props.headerButtonVariant}
                      buttonIcon={props.headerButtonIcon}
                      onClose={() => emit('close')}
                    >
                      {{
                        title: slots.title,
                        button: slots.closeButton
                      }}
                    </ModalHeader>
                }
                {slots.body
                  ? slots.body(
                      { onClose: () => emit('close') }
                    )
                  : <ModalBody
                      content={props.content}
                      icon={props.bodyIcon}
                      iconSize={props.bodyIconSize}
                      style={props.bodyStyle}
                      iconStyle={props.bodyIconStyle}
                      contentStyle={props.bodyContentStyle}
                    >
                      {{
                        content: slots.content
                      }}
                    </ModalBody>
                }
            </>
          }
        </div>
      </>
    )
  }
})

// react/src/components/Modal/Modal.tsx
import { FC } from "react";
import cn from 'classnames'
import { ModalProps } from "./types";
import {
  modalBackdropStyle,
  modalWindowStyle
} from "@shared/components/modal/styles.css";
import {
  bodyIconStyle as _bodyIconStyle,
  bodyContentStyle as _bodyContentStyle,
  bodyStyle as _bodyStyle
} from "@shared/components/modal/modules/body/styles.css";
import {
  headerStyle as _headerStyle,
  headerTitleStyle as _headerTitleStyle,
  headerButtonStyle as _headerButtonStyle
} from "@shared/components/modal/modules/header/styles.css";
import { ModalBody } from "./modules/ModalBody";
import { ModalHeader } from "./modules/ModalHeader/ModalHeader";

export const Modal: FC<ModalProps> = ({
  title = '',
  content = '',
  isCloseByBackdropClick = true,
  zIndex = 1,
  attributes = {},
  backdropStyle = modalBackdropStyle,
  windowStyle = modalWindowStyle,
  onClose = () => {},
  children,
  renderHeader,
  renderBody,
  renderContent,
  /** modal body props pass */
  bodyIcon = 'ri-information-line',
  bodyIconSize = 'medium',
  bodyStyle = _bodyStyle,
  bodyIconStyle = _bodyIconStyle,
  bodyContentStyle = _bodyContentStyle,
  /** modal header props pass */
  headerStyle = _headerStyle,
  headerTitleStyle = _headerTitleStyle,
  headerButtonStyle = _headerButtonStyle,
  headerButtonIcon = 'ri-close-line',
  headerButtonSize = 'medium',
  headerButtonVariant = 'secondary',
  renderHeaderTitle,
  renderHeaderButton
}) => (
  <>
    <div
      className={cn({[backdropStyle]: backdropStyle})}
      style={{ zIndex }}
      onClick={isCloseByBackdropClick ? () => onClose() : undefined}
    ></div>
    <div
      {...attributes}
      className={cn({[windowStyle]: windowStyle})}
      style={{ zIndex }}
    >
      {children
        ? children
        : <>
            {renderHeader
              ? renderHeader()
              : <ModalHeader
                  title={title}
                  buttonIcon={headerButtonIcon}
                  buttonSize={headerButtonSize}
                  buttonVariant={headerButtonVariant}
                  style={headerStyle}
                  titleStyle={headerTitleStyle}
                  buttonStyle={headerButtonStyle}
                  renderTitle={renderHeaderTitle}
                  renderButton={renderHeaderButton}
                  onClose={onClose}
                />
            }
            {renderBody
              ? renderBody()
              : <ModalBody
                  content={content}
                  icon={bodyIcon}
                  iconSize={bodyIconSize}
                  style={bodyStyle}
                  iconStyle={bodyIconStyle}
                  contentStyle={bodyContentStyle}
                  children={renderContent ? renderContent() : null}
                />
            }
          </>
      }
    </div>
  </>
)
