// react/src/components/table/modules/cell/TableCell.tsx
import { ColumnKey } from "@shared/components/table/types";
import { FC, ReactNode } from "react";
import cn from 'classnames';
import { TableCellStylingProps } from "../../types";
import { tableCellStyle, tableCellVariants } from "@shared/components/table/cell/styles.css";
import { useTablePropsProvided } from "../../hooks/use-table-props-provided";
import { useTableColStyling } from "../../hooks/use-col-styling";

type TableCellProps = {
  colKey: ColumnKey
  children?: ReactNode
} & TableCellStylingProps

export const TableCell: FC<TableCellProps> = ({
  cellStyle = tableCellStyle,
  cellVariants = tableCellVariants,
  colKey,
  children = null
}) => {
  const tableProps = useTablePropsProvided()
  const { computeWidth } = useTableColStyling()
  const isHidden = tableProps.hiddenColumnKeys?.includes(colKey)
  return (
    isHidden
      ? <></>
      : <td
        className={cn(
          cellStyle,
          cellVariants[tableProps.size || 'medium']
        )}
        style={{width: computeWidth(colKey)}}
      >
        {children}
      </td>
  )
}

// vue/src/components/table/modules/cell/TableCell.tsx
import { ExtractPublicPropTypes, defineComponent, inject, computed } from 'vue'
import { useColStyling } from '../../hooks/use-col-styling'
import { defaultProvidedTableOptions, tableConfigSymbol, tableRowPropsSymbol } from '../../common'
import { ProvidedTableConfig, TableRowProps } from '../../types'
import { definePropType } from '../../../../utils'
import { tableCellStyle, tableCellVariants } from '../../../../../../shared/components/table/cell/styles.css'
import { ColumnKey } from '../../../../../../shared/components/table/types'

export const tableCellStylingProps = {
	cellStyle: {
		type: String,
		default: tableCellStyle,
	},
	cellVariants: {
		type: Object,
		default: tableCellVariants,
	},
}

export const tableCellProps = {
	...tableCellStylingProps,
	colKey: {
		type: definePropType<ColumnKey>(String),
		default: ''
	}
} as const

export type TableCellProps = ExtractPublicPropTypes<typeof tableCellProps>

export const TableCell = defineComponent({
	name: 'TableCell',
	props: tableCellProps,
	setup(props, { attrs, slots }) {
		const { props: tableProps, provided: tableControlsProvided } = inject<ProvidedTableConfig>(tableConfigSymbol, { ...defaultProvidedTableOptions })
		const { hiddenColumnKeys } = tableControlsProvided

		const rowProps = inject<TableRowProps>(tableRowPropsSymbol, {
			selected: computed(() => false),
			nodes: [],
			depth: 0
		})
		const { computeColumnStyles } = useColStyling(tableProps, hiddenColumnKeys)
		const colStyles = computed(() => (
			props.colKey
				? computeColumnStyles(props.colKey)
				: {}
		))
		const isHidden = computed(() => hiddenColumnKeys.value.includes(props.colKey))
		return () => (
			isHidden.value
				? <></>
				: <td
					{...attrs}
					class={`
						${props.cellStyle}
						${props.cellVariants[tableProps.size]}
						${rowProps.selected.value && props.cellVariants.selected}
					`}
					style={colStyles.value}
				>
					{slots.default && slots.default()}
				</td>
		)
	}
})
