// vue/src/components/button/Button.vue
<script setup lang="ts">
import cn from 'classnames'
import { computed, ExtractPublicPropTypes, inject, ref } from 'vue';
import { $buttonGroupProvided, ButtonGroupProvided } from '../buttonGroup/ButtonGroup';
import { buttonProps } from './button.modules';


const props = defineProps(buttonProps)
export type ButtonProps = ExtractPublicPropTypes<typeof props>
const emit = defineEmits<{
  click: [e: Event]
}>()
const { props: groupProps, emit: groupEmit } = inject<ButtonGroupProvided>($buttonGroupProvided, { props: undefined, emit: undefined })
const $el = ref()

const isInGroup = computed(() => Boolean(groupProps))

const isActive = computed(() => props.active || (isInGroup.value && groupProps?.value && groupProps.value === props.groupKey))

const handleClick = (e: Event) => {
  if (props.disabled) return
  if (props.groupKey && !isActive.value && groupEmit) {
    groupEmit('change', props.groupKey)
  }
  emit('click', e)
}

const isLast = computed(() => isInGroup.value && !$el.value?.nextElementSibling)
const isMiddle = computed(() => isInGroup.value && Boolean($el.value?.previousElementSibling && $el.value?.nextElementSibling))
const isFirst = computed(() => isInGroup.value && !$el.value?.previousElementSibling)
</script>
<template>
  <button
    v-bind="$attrs"
    ref='$el'
    :class="[
        cn({[props.style]: props.style}),

        {
          [cn({
            [props.variants.disabled]: props.variants.disabled
          })]: props.variants && props.disabled
        },
        {
          [cn({
            [props.variants.inGroup]: props.variants.inGroup
          })]: props.variants && isInGroup
        },
        {
          [cn({
            [props.variants.disabled]: props.variants.disabled
          })]: props.variants && props.disabled
        },
        {
          [cn({
            [props.variants.active]: props.variants.active,
        })]: props.variants && isActive
        },
        {
          [cn({
            [props.variants.first]: props.variants.first,
          })]: props.variants && isFirst
        },
        {
          [cn({
            [props.variants.middle]: props.variants.middle,
          })]: props.variants && isMiddle
        },
        {
          [cn({
            [props.variants.last]: props.variants.last,
          })]: props.variants && isLast
        }
      ]"
      :disabled="props.disabled"
      @click="handleClick"
    >
    <slot />
  </button>
</template>

// react/src/components/Button/Button.tsx
import { FC, SyntheticEvent, useContext, useEffect, useMemo, useRef, useState } from "react"
import cn from 'classnames'
import { ButtonProps } from "./types"
import {
  buttonStyle,
  buttonVariants
} from "@shared/components/button"
import { ButtonGroupContext } from "../ButtonGroup/ButtonGroup"


export const Button: FC<ButtonProps> = ({
  ref = null,
  className = '',
  style = buttonStyle,
  variants = buttonVariants,
  groupKey,
  active = false,
  disabled = false,
  attributes = {},
  children = null,
  onClick = () => false
}) => {
  const groupProps = useContext(ButtonGroupContext)
  const $el = useRef<HTMLButtonElement | null>(null)

  const [mounted, setMounted] = useState(false)

  const isInGroup = useMemo(
    () => groupProps !== undefined,
    [groupProps]
  )
  const isActive = useMemo(
    () => (
      active || (isInGroup && groupProps?.value && groupProps?.value === groupKey)
    ),
    [groupProps, active, isInGroup, groupKey]
  )
  const handleClick = (e: SyntheticEvent) => {
    if (disabled) return
    if (groupProps?.onChange && groupKey && !isActive) {
      groupProps.onChange(groupKey)
    }
    onClick(e)
  }
  const isLast = useMemo(
    () => isInGroup && !$el.current?.nextElementSibling,
    [isInGroup, mounted]
  )
  const isMiddle = useMemo(
    () => isInGroup && Boolean($el.current?.previousElementSibling && $el.current?.nextElementSibling),
    [isInGroup, mounted]
  )
  const isFirst = useMemo(
    () => isInGroup && !$el.current?.previousElementSibling,
    [isInGroup, mounted]
  )
  useEffect(() => {
    setMounted(true)
  }, [])
  return <button
    {...attributes}
    ref={(element) => {
      $el.current = element
      if (typeof ref === 'function') {
        ref(element)
      } else if (ref) ref.current = element
    }}
    className={cn(
      className,
      style,
      {
        [cn({
          [variants.disabled]: variants.disabled
        })]: disabled
      },
      {
        [cn({
          [variants.inGroup]: variants.inGroup
        })]: isInGroup
      },
      {
        [cn({
          [variants.active]: variants.active,
        })]: isActive
      },
      {
        [cn({
          [variants.first]: variants.first,
        })]: isFirst
      },
      {
        [cn({
          [variants.middle]: variants.middle,
        })]: isMiddle
      },
      {
        [cn({
          [variants.last]: variants.last,
        })]: isLast
      }
    )}
    disabled={disabled}
    onClick={handleClick}
  >
    {children}
  </button>
}
