// vue/src/components/button/index.tsx
import { definePropType } from '../../utils'
import { ExtractPublicPropTypes, defineComponent } from 'vue'

import {
	buttonStyle,
	buttonVariants,
	type ButtonSize,
	type ButtonVariant
} from '@shared/components/button'

const buttonProps = {
	style: {
		type: String,
		default: buttonStyle
	},
	variants: {
		type: Object,
		default: buttonVariants
	},
	variant: {
		type: definePropType<ButtonVariant>(String),
		default: 'primary'
	},
	size: {
		type: definePropType<ButtonSize>(String),
		default: 'medium'
	},
	disabled: {
		type: definePropType<boolean>(Boolean),
		default: false
	},
	whenClick: {
		type: definePropType<(e: Event) => {}>(Function),
		default: () => {}
	}
} as const

export type ButtonProps = ExtractPublicPropTypes<typeof buttonProps>

export const Button = defineComponent({
	name: 'Button',
	props: buttonProps,
	setup(props, {attrs, slots}) {
			return () => (
				<button
					{...attrs}
					class={`
						${props.style}
						${(props.variants && !props.disabled) && props.variants[props.variant]}
						${props.variants && props.variants[props.size]}
						${props.disabled && `${props.variants.disabled} ${props.variants[`disabled_${props.variant}`]}`}
					`}
					disabled={props.disabled}
					onClick={(e: Event) => !props.disabled && props.whenClick(e)}
				>
					{slots.default && slots.default()}
				</button>
			)
	},
})

export {
	buttonStyle,
	buttonVariants
}

// react/src/components/button/index.tsx
import { ButtonHTMLAttributes, ReactNode, SyntheticEvent } from "react"

import {
	buttonStyle,
	buttonVariants,
	type ButtonVariant,
	type ButtonSize
} from "@shared/components/button"

export type ButtonProps = {
	style?: string,
	variants?: Record<string, string>
	variant?: ButtonVariant
	size?: ButtonSize
	disabled?: boolean
	attributes?: ButtonHTMLAttributes<HTMLButtonElement>
	children?: ReactNode
	onClick?: (e: SyntheticEvent) => void
}

export const Button = ({
	style = buttonStyle,
	variants = buttonVariants,
	variant = 'primary',
	size = 'medium',
	disabled = false,
	attributes = {},
	children = null,
	onClick = () => false
}: ButtonProps) => {
	return <button
		{...attributes}
		className={`
			${style}
			${(variants && !disabled) && variants[variant]}
			${variants && variants[size]}
			${disabled && `${variants.disabled} ${variants[`disabled_${variant}`]}`}
		`}
		disabled={disabled}
		onClick={(e: SyntheticEvent) => !disabled && onClick(e)}
	>
		{children}
	</button>
}

export { buttonStyle, buttonVariants }
