// react/src/components/input/index.tsx
import { SyntheticEvent, useId, useState } from "react"
import { InputProps } from "./types"

import {
	inputFieldBoxStyle,
	inputFieldBoxVariants,
	inputFieldStyle,
	inputFieldVariants,
	inputLabelStyle,
	inputLabelVariants,
	inputStyle,
	inputVariants
} from '@shared/components/input'

export const Input = ({
	style = inputStyle,
	variants = inputVariants,
	labelStyle = inputLabelStyle,
	labelVariants = inputLabelVariants,
	fieldBoxStyle = inputFieldBoxStyle,
	fieldBoxVariants = inputFieldBoxVariants,
	fieldStyle = inputFieldStyle,
	fieldVariants = inputFieldVariants,
	attributes = {},
	id = '',
	type = 'text',
	label = '',
	value = '',
	disabled = false,
	size = 'medium',
	onChange = () => {},
	onInput = () => {},
	children = null,
	prefix = null,
	postfix = null
}: InputProps) => {
	const inputId = id ? id : useId()

	const [hover, setHover] = useState(false)
	const [focus, setFocus] = useState(false)

	const handleMouseIn = () => {
		if (disabled) return
		setHover(true)
	}
	const handleMouseOut = () => setHover(false)

	const handleFocus = () => {
		if (disabled) return
		setFocus(true)
	}
	const handleBlur = () => setFocus(false)

	return <div
		{...attributes}
		className={`
			${style}
			${variants[size]}
			${disabled && variants.disabled}
			${hover && variants.hover}
			${focus && variants.focus}
		`}
		onMouseEnter={handleMouseIn}
		onMouseLeave={handleMouseOut}
	>
		{label && (
			<label
				htmlFor={inputId}
				className={`
					${labelStyle}
					${labelVariants[size]}
					${disabled && labelVariants.disabled}
					${hover && labelVariants.hover}
					${(focus || value) && labelVariants.focus}
				`}
			>
				{label}
			</label>
		)}
		{typeof children === 'function'
			? children({ hover, focus, handleFocus, handleBlur })
			: children !== null
				? children
				: <div
					className={`
						${fieldBoxStyle}
						${fieldBoxVariants[size]}
						${disabled && fieldBoxVariants.disabled}
						${hover && fieldBoxVariants.hover}
						${focus && fieldBoxVariants.focus}
					`}
				>
					{typeof prefix === 'function'
						? prefix()
						: prefix
					}
					<input
						id={inputId}
						className={`
							${fieldStyle}
							${fieldVariants[size]}
							${disabled && fieldVariants.disabled}
							${hover && fieldVariants.hover}
							${focus && fieldVariants.focus}
						`}
						type={type}
						value={value}
						onFocus={handleFocus}
						onBlur={handleBlur}
						onChange={(e: SyntheticEvent) => onChange((e.target as HTMLInputElement).value)}
						onInput={(e: SyntheticEvent) => onInput((e.target as HTMLInputElement).value)}
					/>
					{typeof postfix === 'function'
						? postfix()
						: postfix
					}
				</div>
		}
	</div>
}

export {
	type InputProps,
	inputStyle,
	inputVariants,
	inputLabelStyle,
	inputLabelVariants,
	inputFieldBoxStyle,
	inputFieldBoxVariants,
	inputFieldStyle,
	inputFieldVariants
}

// vue/src/components/input/index.tsx
import { definePropType } from '../../utils'
import { ExtractPublicPropTypes, defineComponent, ref } from 'vue'
import { v4 as uuid } from 'uuid'
import {
	inputFieldBoxStyle,
	inputFieldBoxVariants,
	inputFieldStyle,
	inputFieldVariants,
	inputLabelStyle,
	inputLabelVariants,
	inputStyle,
	inputVariants,
	type InputEmitter,
	type InputSize,
	type InputValue,
	type InputType, 
	type InputId
} from '@shared/components/input'

const inputProps = {
	style: {
		type: String,
		default: inputStyle
	},
	variants: {
		type: Object,
		default: inputVariants
	},
	labelStyle: {
		type: String,
		default: inputLabelStyle
	},
	labelVariants: {
		type: Object,
		default: inputLabelVariants
	},
	fieldBoxStyle: {
		type: String,
		default: inputFieldBoxStyle
	},
	fieldBoxVariants: {
		type: Object,
		default: inputFieldBoxVariants
	},
	fieldStyle: {
		type: String,
		default: inputFieldStyle
	},
	fieldVariants: {
		type: Object,
		default: inputFieldVariants
	},
	id: {
		type: definePropType<InputId>(String),
		default: ''
	},
	type: {
		type: definePropType<InputType>(String),
		default: 'text'
	},
	label: {
		type: definePropType<string>(String),
		default: ''
	},
	value: {
		type: definePropType<InputValue>(String),
		default: ''
	},
	disabled: {
		type: definePropType<boolean>(Boolean),
		default: false
	},
	size: {
		type: definePropType<InputSize>(String),
		default: 'medium'
	},
	whenChange: {
		type: definePropType<InputEmitter>(Function),
		default: () => {}
	},
	whenInput: {
		type: definePropType<InputEmitter>(Function),
		default: () => {}
	}
}

export type InputProps = ExtractPublicPropTypes<typeof inputProps>

export const Input = defineComponent({
	name: 'Input',
	props: inputProps,
	setup(props, { slots, attrs }) {
		const id = props.id ? props.id : uuid()

		const hover = ref(false)
		const focus = ref(false)

		const handleMouseIn = () => {
			if (props.disabled) return
			hover.value = true
		}
		const handleMouseOut = () => hover.value = false

		const handleFocus = () => {
			if (props.disabled) return
			focus.value = true
		}
		const handleBlur = () => focus.value = false

		return () => (
			<div
				{...attrs}
				class={`
					${props.style}
					${props.variants[props.size]}
					${props.disabled && props.variants.disabled}
					${hover.value && props.variants.hover}
					${focus.value && props.variants.focus}
				`}
				onMouseenter={handleMouseIn}
				onMouseleave={handleMouseOut}
			>
				{props.label
					? <label
							for={id}
							class={`
								${props.labelStyle}
								${props.labelVariants[props.size]}
								${props.disabled && props.labelVariants.disabled}
								${hover.value && props.labelVariants.hover}
								${(focus.value || props.value) && props.labelVariants.focus}
							`}
						>
						{props.label}
					</label>
					: slots.label && slots.label()
				}
				{slots.default
					? slots.default({
							hover,
							focus,
							handleFocus,
							handleBlur
						})
					: 
						<div
							class={`
								${props.fieldBoxStyle}
								${props.fieldBoxVariants[props.size]}
								${props.disabled && props.fieldBoxVariants.disabled}
								${hover.value && props.fieldBoxVariants.hover}
								${focus.value && props.fieldBoxVariants.focus}
							`}
						>
							{slots.prefix && slots.prefix()}
							<input
								id={id}
								class={`
									${props.fieldStyle}
									${props.fieldVariants[props.size]}
									${props.disabled && props.fieldVariants.disabled}
									${hover.value && props.fieldVariants.hover}
									${focus.value && props.fieldVariants.focus}
								`}
								type={props.type}
								value={props.value}
								onFocus={handleFocus}
								onBlur={handleBlur}
								onChange={(e: Event) => props.whenChange((e.target as HTMLInputElement).value)}
								onInput={(e: Event) => props.whenInput((e.target as HTMLInputElement).value)}
							/>
							{slots.postfix && slots.postfix()}
						</div>
				}
			</div>
		)
	}
})
export {
	inputFieldBoxStyle,
	inputFieldBoxVariants,
	inputFieldStyle,
	inputFieldVariants,
	inputLabelStyle,
	inputLabelVariants,
	inputStyle,
	inputVariants
}
