// vue/src/components/table/modules/headerCell/TableHeaderCell.tsx
import { defineComponent, ExtractPublicPropTypes, inject, computed, CSSProperties } from 'vue'
import { definePropType } from '../../../../utils'
import { ProvidedTableConfig, TableHeaderProps } from '../../types'
import { defaultProvidedTableOptions, tableConfigSymbol, tableHeaderPropsSymbol } from '../../common'
import { useColStyling } from '../../hooks/use-col-styling'
import {
	tableHeaderCellStyle,
	tableHeaderCellVariants,
	tableHeaderCellIconStyle,
	tableHeaderCellIconVariants,
	tableHeaderCellLabelStyle
} from './index'
import { ColumnKey, Sorting } from '@shared/components/table/types'

export const tableHeaderCellProps = {
	style: {
		type: String,
		default: tableHeaderCellStyle
	},
	variants: {
		type: Object,
		default: tableHeaderCellVariants
	},
	labelStyle: {
		type: String,
		default: tableHeaderCellLabelStyle
	},
	iconStyle: {
		type: String,
		default: tableHeaderCellIconStyle
	},
	iconVariants: {
		type: Object,
		default: tableHeaderCellIconVariants
	},
	colKey: {
		type: definePropType<ColumnKey>(String),
		required: true,
	},
	sortable: {
		type: Boolean,
		default: false,
	},
	whenChangeSort: {
		type: definePropType<(colKey: string, newSortValue: Sorting['value']) => void>(Function),
		default: () => () => {}
	}
} as const

export type TableHeaderCellProps = ExtractPublicPropTypes<typeof tableHeaderCellProps>

export const TableHeaderCell = defineComponent({
	name: 'TableHeaderCell',
	props: tableHeaderCellProps,
	setup(props, { attrs, slots }) {
		const headerProps = inject<TableHeaderProps>(tableHeaderPropsSymbol)
		const { props: tableProps, provided: tableControlsProvided } = inject<ProvidedTableConfig>(tableConfigSymbol, { ...defaultProvidedTableOptions })
		const { hiddenColumnKeys } = tableControlsProvided

		const { computeColumnStyles } = useColStyling(tableProps, hiddenColumnKeys)
		const colWidthStyles = computed(() => (
			props.colKey
				? computeColumnStyles(props.colKey)
				: {}
		) as CSSProperties)

		const column = computed(() => tableProps?.columns?.find((column) => column.key === props.colKey))

		const isColumnSortable = computed(() => headerProps?.sorting?.key === props.colKey || (column.value?.sortable ?? props.sortable))

		const isHidden = computed(() => hiddenColumnKeys.value.includes(props.colKey))

		const sort = () => {
			if (!headerProps?.sorting) return
			const { sorting } = headerProps
			let newSortValue: Sorting['value'] = ''
			if (props.colKey === sorting.key) {
				switch (sorting.value) {
					case 'asc':
						newSortValue = 'desc'
						break
					case 'desc':
						newSortValue = ''
						break
					default:
						newSortValue = 'asc'
				}
			} else {
				newSortValue = 'asc'
			}
			props.whenChangeSort(props.colKey, newSortValue)
		}

		const handleSort = () => isColumnSortable.value && sort()

		return () => (
			isHidden.value
				? <></>
				: <th
					{...attrs}
					class={`
						${props.style}
						${isColumnSortable.value && props.variants.sortable}
					`}
					style={colWidthStyles.value}
					onClick={handleSort}
				>
					<div class={props.labelStyle}>
						{column.value
							? column.value.label
								? <span>{column.value.label}</span>
								: null
							: slots.default
								? slots.default()
								: null
						}
						{(headerProps?.sorting && headerProps?.sorting.key === props.colKey)
							? <span
									class={`
										${props.iconStyle}
										${props.iconVariants[headerProps.sorting.value]}
										${!headerProps?.sorting.value && props.iconVariants.invisible}
									`}
								></span>
							: null
						}
					</div>
				</th>
		)
	}
})


export {
	tableHeaderCellStyle,
	tableHeaderCellVariants,
	tableHeaderCellIconStyle,
	tableHeaderCellIconVariants,
	tableHeaderCellLabelStyle
}

// react/src/components/table/modules/headerCell/TableHeaderCell.tsx
import { ColumnKey, Sorting } from "@shared/components/table/types";
import { FC, ReactNode } from "react";
import cn from 'classnames';
import { StyleVariants } from "src/components/types";
import { ChangeSortHandler } from "../../types";
import {
	tableHeaderCellStyle,
	tableHeaderCellVariants,
	tableHeaderCellIconStyle,
	tableHeaderCellIconVariants,
	tableHeaderCellLabelStyle
} from '@shared/components/table/headerCell/styles.css'
import { useTablePropsProvided } from "../../hooks/use-table-props-provided";
import { useTableColStyling } from "../../hooks/use-col-styling";

type TableHeaderCellProps = {
  style?: string
  variants?: StyleVariants
  labelStyle?: string
  iconStyle?: string
  iconVariants?: StyleVariants
  colKey: ColumnKey
  sortable?: boolean
  onChangeSort?: ChangeSortHandler
  children: ReactNode
}

export const TableHeaderCell: FC<TableHeaderCellProps> = ({
  style = tableHeaderCellStyle,
  variants = tableHeaderCellVariants,
  labelStyle = tableHeaderCellLabelStyle,
  iconStyle = tableHeaderCellIconStyle,
  iconVariants = tableHeaderCellIconVariants,
  sortable = false,
  onChangeSort = () => {},
  colKey,
  children = null
}) => {
  const { hiddenColumnKeys = [], sorting, columns } = useTablePropsProvided()
  const { computeWidth } = useTableColStyling()
  const isHidden = hiddenColumnKeys.includes(colKey)
  const sort = () => {
    if (!sorting) return
    let newSortValue: Sorting['value'] = ''
    if (colKey === sorting.key) {
      switch (sorting.value) {
        case 'asc':
          newSortValue = 'desc'
          break
        case 'desc':
          newSortValue = ''
          break
        default:
          newSortValue = 'asc'
      }
    } else {
      newSortValue = 'asc'
    }
    onChangeSort(colKey, newSortValue)
  }
  const column = columns.find((col) => col.key === colKey)
  const isColumnSortable = sorting?.key === colKey || (column?.sortable ?? sortable)
  const handleSort = () => isColumnSortable && sort()
  return isHidden
    ? null
    : <div
      className={`${style} ${sortable ? variants.sortable : ''}`}
      style={{width: computeWidth(colKey)}}
      onClick={handleSort}
    >
      <div className={labelStyle}>
        {column
          ? column.label
            ? column.label
            : null
          : children
        }
        {(sorting && sorting.key === colKey)
          ? <span
            className={cn(
              iconStyle,
              sorting.value ? iconVariants[sorting.value] : iconVariants.invisible,
            )}
          ></span>
          : null
        }
      </div>
    </div>
}
