// react/src/components/Spoiler/Spoiler.tsx
import { FC, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { SpoilerProps } from "./types";
import cn from 'classnames'
import {
  spoilerContentStyle,
  spoilerContentVariants,
  spoilerHeaderStyle,
  spoilerHeaderVariants,
  spoilerStyle,
  spoilerTitleStyle,
  spoilerTitleVariants,
  spoilerVariants
} from "@shared/components/spoiler";
import { Icon } from "../Icon";
import { Button } from "../Button";
import { useAccordionProvided } from "../Accordion";

export const Spoiler: FC<SpoilerProps> = ({
  ref = null,
  style = spoilerStyle,
  variants = spoilerVariants,
  headerStyle = spoilerHeaderStyle,
  headerVariants = spoilerHeaderVariants,
  titleStyle = spoilerTitleStyle,
  titleVariants = spoilerTitleVariants,
  contentStyle = spoilerContentStyle,
  contentVariants = spoilerContentVariants,
  openedIcon = 'ri-arrow-up-s-line',
  closedIcon = 'ri-arrow-down-s-line',
  title = '',
  groupKey = '',
  opened = false,
  disabled = false,
  attributes = {},
  size = 'medium',
  onToggle = () => {},
  renderExpander,
  renderTitle,
  children,
}) => {
  const $el = useRef<HTMLDivElement | null>(null)
  const accordion = useAccordionProvided()

  const [mounted, setMounted] = useState(false)
  useEffect(() => {
    setMounted(true)
  }, [])

  const isOpen = useMemo(() => (
    opened || groupKey === accordion?.opened
  ), [opened, groupKey, accordion])

  const isInGroup = useMemo(() => (
    Boolean(accordion)
  ), [accordion])

  const isLast = useMemo(() => (
    isInGroup && !$el.current?.nextElementSibling
  ), [mounted])

  const isMiddle = useMemo(() => (
    isInGroup && Boolean($el.current?.previousElementSibling && $el.current?.nextElementSibling)
  ), [mounted])

  const isFirst = useMemo(() => (
    isInGroup && !$el.current?.previousElementSibling
  ), [mounted])

  const handleToggle = useCallback(() => {
    if (accordion && accordion.onToggle) {
      accordion.onToggle(
        groupKey !== accordion.opened
          ? groupKey
          : undefined
      )
    }
    onToggle(!isOpen)
  }, [accordion])
  return (
    <div
      ref={(element) => {
        $el.current = element
        if (typeof ref === 'function') {
          ref(element)
        } else if (ref) ref.current = element
      }}
      {...attributes}
      className={cn({
        [style]: style,
        [variants[size]]: variants[size] && size,
        [variants.disabled]: variants.disabled && disabled,
        [variants.opened]: isOpen,
        [variants.last]: variants.last && isLast,
        [variants.middle]: variants.middle && isMiddle,
        [variants.first]: variants.first && isFirst
      })}
    >
      <div className={cn({
        [headerStyle]: headerStyle,
        [headerVariants[size]]: headerVariants[size] && size,
        [headerVariants.disabled]: headerVariants.disabled && disabled,
        [headerVariants.opened]: isOpen
      })}>
        {renderTitle
          ? typeof renderTitle === 'function'
            ? renderTitle({toggle: handleToggle})
            : renderTitle
          : <div className={cn({
              [titleStyle]: titleStyle,
              [titleVariants[size]]: titleVariants[size] && size,
              [titleVariants.disabled]: titleVariants.disabled && disabled,
              [titleVariants.opened]: isOpen
            })}>
              {title}
            </div>
        }
        {renderExpander
          ? typeof renderExpander === 'function'
            ? renderExpander({toggle: handleToggle})
            : renderExpander
          : <Button
              variant='info'
              size={size}
              onClick={() => handleToggle()}
            >
              <Icon
                name={isOpen ? openedIcon : closedIcon}
                size={size}
              />
            </Button>
        }
      </div>
      <div className={cn({
        [contentStyle]: contentStyle,
        [contentVariants[size]]: contentVariants[size] && size,
        [contentVariants.disabled]: contentVariants.disabled && disabled,
        [contentVariants.opened]: contentVariants.opened && isOpen
      })}>
        {children}
      </div>
    </div>
  )
}

// vue/src/components/spoiler/Spoiler.tsx
import { SpoilerEmitters, SpoilerSize } from "@shared/components/spoiler/types";
import cn from 'classnames'
import { definePropType } from "../../utils";
import { computed, defineComponent, ExtractPublicPropTypes, inject, ref } from "vue";
import { Button } from "../button";
import { Icon } from "../icon";
import {
  spoilerContentStyle,
  spoilerContentVariants,
  spoilerHeaderStyle,
  spoilerHeaderVariants,
  spoilerStyle,
  spoilerTitleStyle,
  spoilerTitleVariants,
  spoilerVariants
} from "@shared/components/spoiler";
import { $accordionSymbol, AccordionProvided } from "../accordion/Accordion";

export const spoilerProps = {
  style: {
    type: String,
    default: spoilerStyle
  },
  variants: {
    type: Object,
    default: spoilerVariants
  },
  headerStyle: {
    type: String,
    default: spoilerHeaderStyle
  },
  headerVariants: {
    type: Object,
    default: spoilerHeaderVariants
  },
  titleStyle: {
    type: String,
    default: spoilerTitleStyle
  },
  titleVariants: {
    type: Object,
    default: spoilerTitleVariants
  },
  contentStyle: {
    type: String,
    default: spoilerContentStyle
  },
  contentVariants: {
    type: Object,
    default: spoilerContentVariants
  },
  openedIcon: {
    type: String,
    default: 'ri-arrow-up-s-line'
  },
  closedIcon: {
    type: String,
    default: 'ri-arrow-down-s-line'
  },
  title: {
    type: definePropType<string>(String),
    default: ''
  },
  groupKey: {
    type: definePropType<string | symbol>(String),
    default: ''
  },
  opened: {
    type: definePropType<boolean>(Boolean),
    default: false
  },
  disabled: {
    type: definePropType<boolean>(Boolean),
    default: false
  },
  size: {
    type: definePropType<SpoilerSize>(String),
    default: 'medium'
  }
}

export type SpoilerProps = ExtractPublicPropTypes<typeof spoilerProps>

export const spoilerEmitters: SpoilerEmitters = {
  toggle: (value) => typeof value === 'boolean'
}

export const Spoiler = defineComponent({
  name: 'Spoiler',
  props: spoilerProps,
  emits: spoilerEmitters,
  setup(props, { slots, attrs, emit }) {
    const accordion = inject<AccordionProvided | undefined>($accordionSymbol, undefined)

    const $el = ref()

    const isInGroup = computed(() => Boolean(accordion))

    const isLast = computed(() => isInGroup.value && !$el.value?.nextElementSibling)
    const isMiddle = computed(() => isInGroup.value && Boolean($el.value?.previousElementSibling && $el.value?.nextElementSibling))
    const isFirst = computed(() => isInGroup.value && !$el.value?.previousElementSibling)

    const opened = computed(() => props.opened || accordion?.openedKey.value === props.groupKey)

    const handleToggle = () => {
      if (props.disabled) return
      if (accordion) {
        if (accordion.openedKey.value === props.groupKey) {
          accordion.emit('toggle')
        } else {
          accordion.emit('toggle', props.groupKey)
        }
      }
      emit('toggle', !opened.value)
    }
    return () => (
      <div
        {...attrs}
        ref={$el}
        class={cn({
          [props.style]: props.style,
          [props.variants[props.size]]: props.variants[props.size] && props.size,
          [props.variants.disabled]: props.variants.disabled && props.disabled,
          [props.variants.opened]: props.variants.opened && opened.value,
          [props.variants.last]: props.variants.last && isLast.value,
          [props.variants.middle]: props.variants.middle && isMiddle.value,
          [props.variants.first]: props.variants.first && isFirst.value
        })}
      >
        <div class={cn({
          [props.headerStyle]: props.headerStyle,
          [props.headerVariants[props.size]]: props.headerVariants[props.size] && props.size,
          [props.headerVariants.disabled]: props.headerVariants.disabled && props.disabled,
          [props.headerVariants.opened]: props.headerVariants.opened && opened.value
        })}>
          {slots.title
            ? slots.title({
                toggle: handleToggle
              })
            : <div class={cn({
                [props.titleStyle]: props.titleStyle,
                [props.titleVariants[props.size]]: props.titleVariants[props.size] && props.size,
                [props.titleVariants.disabled]: props.titleVariants.disabled && props.disabled,
                [props.titleVariants.opened]: props.titleVariants.opened && opened.value
              })}>
                {props.title}
              </div>
          }
          {slots.expander
            ? slots.expander()
            : <Button
                variant='info'
                size={props.size}
                onClick={() => handleToggle()}
              >
                <Icon
                  name={opened.value ? props.openedIcon : props.closedIcon}
                  size={props.size}
                />
              </Button>
          }
        </div>
        <div class={cn({
          [props.contentStyle]: props.contentStyle,
          [props.contentVariants[props.size]]: props.contentVariants[props.size] && props.size,
          [props.contentVariants.disabled]: props.contentVariants.disabled && props.disabled,
          [props.contentVariants.opened]: props.contentVariants.opened && opened.value
        })}>
          {slots.default && slots.default()}
        </div>
      </div>
    )
  }
})
