// vue/src/components/modal/modules/ModalHeader/ModalHeader.tsx
import { definePropType } from "../../../../utils"
import cn from 'classnames'
import { headerButtonIcon, headerButtonSize, headerButtonVariant, headerStyle, headerTitleStyle, headerButtonStyle } from "./stylingProps"
import { defineComponent, ExtractPublicPropTypes } from "vue"
import { Button } from "../../../button"
import { Icon } from "../../../icon"


const modalHeaderStylingProps = {
  style: headerStyle,
  titleStyle: headerTitleStyle,
  buttonStyle: headerButtonStyle,
  buttonIcon: headerButtonIcon,
  buttonSize: headerButtonSize,
  buttonVariant: headerButtonVariant
}

export const modalHeaderProps = {
  title: {
    type: definePropType<string>(String),
    default: ''
  },
  ...modalHeaderStylingProps
} as const

export type ModalHeaderProps = ExtractPublicPropTypes<typeof modalHeaderProps>

export type ModalEmitters = {
  close: () => void
}

export const modalEmitters: ModalEmitters = {
  close: () => true
}

export const ModalHeader = defineComponent({
  props: modalHeaderProps,
  emits: modalEmitters,
  setup(props, {slots, emit}) {
    return () => (
      <div class={cn({[props.style]: props.style})}>
        {slots.title
          ? slots.title()
          : <div class={cn({[props.titleStyle]: props.titleStyle})}>{props.title}</div>
        }
        {slots.button
          ? slots.button(
              { onClose: () => emit('close') }
            )
          : <Button
              class={props.buttonStyle}
              size={props.buttonSize}
              variant={props.buttonVariant}
              onClick={() => emit('close')}
            >
              <Icon
                name={props.buttonIcon}
                size={props.buttonSize}
              />
            </Button>
        }
      </div>
    )
  }
})

// react/src/components/Modal/modules/ModalHeader/ModalHeader.tsx
import { FC } from "react";
import { ModalHeaderProps } from "./types";
import cn from 'classnames'
import {
  headerStyle,
  headerTitleStyle,
  headerButtonStyle
} from '@shared/components/modal/modules/header/styles.css'
import { Button } from "../../../Button";
import { Icon } from "../../../Icon";

export {
  headerStyle as modalHeaderStyle,
  headerTitleStyle as modalHeaderTitleStyle,
  headerButtonStyle as modalHeaderButtonStyle
}

export const ModalHeader: FC<ModalHeaderProps> = ({
  title = '',
  renderTitle,
  renderButton,
  style = headerStyle,
  titleStyle = headerTitleStyle,
  buttonStyle = headerButtonStyle,
  buttonIcon = 'ri-close-line',
  buttonSize = 'medium',
  buttonVariant = 'info',
  onClose = () => {},
}) => (
  <div className={cn({[style]: style})}>
    {renderTitle
      ? renderTitle()
      : <div className={cn({[titleStyle]: titleStyle})}>
          {title}
        </div>
    }
    {renderButton
      ? renderButton()
      : <Button
          className={cn({[buttonStyle]: buttonStyle})}
          size={buttonSize}
          variant={buttonVariant}
          onClick={onClose}
        >
          <Icon name={buttonIcon} size={buttonSize} />
        </Button>
    }
  </div>
)
