// react/src/components/button/Button.tsx
import { FC, SyntheticEvent, useContext, useEffect, useMemo, useRef, useState } from "react"
import cn from 'classnames'
import { ButtonProps } from "./types"
import {
  buttonStyle,
  buttonVariants
} from "../../../../shared/components/button"
import { ButtonGroupContext } from "../buttonGroup/ButtonGroup"


export const Button: FC<ButtonProps> = ({
	ref = null,
	style = buttonStyle,
	variants = buttonVariants,
	groupKey,
	variant = 'primary',
	active = false,
	size = 'medium',
	disabled = false,
	attributes = {},
	children = null,
	onClick = () => false
}) => {
	const groupProps = useContext(ButtonGroupContext)
	const $el = useRef<HTMLButtonElement | null>(null)

	const [mounted, setMounted] = useState(false)

	const isInGroup = useMemo(
		() => groupProps !== undefined,
		[groupProps]
	)
	const isActive = useMemo(
		() => (
			active || (isInGroup && groupProps?.value && groupProps?.value === groupKey)
		),
		[groupProps, active, isInGroup, groupKey]
	)
	const handleClick = (e: SyntheticEvent) => {
		if (disabled) return
		if (groupProps?.onChange && groupKey && !isActive) {
			groupProps.onChange(groupKey)
		}
		onClick(e)
	}
	const isLast = useMemo(
		() => isInGroup && !$el.current?.nextElementSibling,
		[isInGroup, mounted]
	)
	const isMiddle = useMemo(
		() => isInGroup && Boolean($el.current?.previousElementSibling && $el.current?.nextElementSibling),
		[isInGroup, mounted]
	)
	const isFirst = useMemo(
		() => isInGroup && !$el.current?.previousElementSibling,
		[isInGroup, mounted]
	)
	useEffect(() => {
		setMounted(true)
	}, [])
	return <button
		{...attributes}
		ref={(element) => {
			$el.current = element
			if (typeof ref === 'function') {
				ref(element)
			} else if (ref) ref.current = element
		}}
		className={cn(
			style,
			{
				[cn({
					[variants[variant]]: variants[variant]
				})]: variants && !disabled
			},
			{
				[cn({
					[variants[size]]: variants[size]
				})]: variants && size
			},
			{
				[cn({
					[variants.disabled]: variants.disabled
				})]: variants && disabled
			},
			{
				[cn({
					[variants.disabled]: variants.disabled,
					[variants[`${variant}_disabled`]]: variants[`${variant}_disabled`]
				})]: variants && disabled
			},
			{
				[cn({
					[variants.inGroup]: variants.inGroup
				})]: variants && isInGroup
			},
			{
				[cn({
					[variants.active]: variants.active,
					[variants[`${variant}_active`]]: variants[`${variant}_active`]
				})]: variants && isActive
			},
			{
				[cn({
					[variants.first]: variants.first,
					[variants[`${variant}_first`]]: variants[`${variant}_first`]
				})]: variants && isFirst
			},
			{
				[cn({
					[variants.middle]: variants.middle,
					[variants[`${variant}_middle`]]: variants[`${variant}_middle`]
				})]: variants && isMiddle
			},
			{
				[cn({
					[variants.last]: variants.last,
					[variants[`${variant}_last`]]: variants[`${variant}_last`]
				})]: variants && isLast
			}
		)}
		disabled={disabled}
		onClick={handleClick}
	>
		{children}
	</button>
}

// vue/src/components/button/Button.tsx
import { definePropType } from '../../utils'
import { ExtractPublicPropTypes, computed, defineComponent, inject, ref } from 'vue'
import cn from 'classnames'
import {
	buttonStyle,
	buttonVariants,
	type ButtonSize,
	type ButtonVariant
} from '../../../../shared/components/button'
import { $buttonGroupProvided, ButtonGroupProvided } from '../buttonGroup/ButtonGroup'

export const buttonProps = {
	style: {
		type: String,
		default: buttonStyle
	},
	variants: {
		type: Object,
		default: buttonVariants
	},
	groupKey: {
		type: definePropType<string | number | null>(null),
		default: null
	},
	variant: {
		type: definePropType<ButtonVariant>(String),
		default: 'primary'
	},
	active: {
		type: definePropType<boolean>(Boolean),
		default: false
	},
	size: {
		type: definePropType<ButtonSize>(String),
		default: 'medium'
	},
	disabled: {
		type: definePropType<boolean>(Boolean),
		default: false
	}
} as const

export type ButtonProps = ExtractPublicPropTypes<typeof buttonProps>

export type ButtonEmitters = {
	click: (e: Event) => void
}

const buttonEmitters: ButtonEmitters = {
	click: (e) => e?.type === 'click'
}

export const Button = defineComponent({
	name: 'Button',
	props: buttonProps,
	emits: buttonEmitters,
	setup(props, {attrs, slots, emit}) {
		const { props: groupProps, emit: groupEmit } = inject<ButtonGroupProvided>($buttonGroupProvided, { props: {}, emit: () => {} })
		const $el = ref()

		const isInGroup = computed(() => Boolean(Object.keys(groupProps).length))

		const isActive = computed(() => props.active || (isInGroup.value && groupProps.value && groupProps.value === props.groupKey))

		const handleClick = (e: Event) => {
			if (props.disabled) return
			if (props.groupKey && !isActive.value) {
				groupEmit('change', props.groupKey)
			}
			emit('click', e)
		}

		const isLast = computed(() => isInGroup.value && !$el.value?.nextElementSibling)
		const isMiddle = computed(() => isInGroup.value && Boolean($el.value?.previousElementSibling && $el.value?.nextElementSibling))
		const isFirst = computed(() => isInGroup.value && !$el.value?.previousElementSibling)

		return () => (
			<button
				{...attrs}
				ref={$el}
				class={[
					props.style,
					{
						[cn({
							[props.variants[props.variant]]: props.variants[props.variant]
						})]: props.variants && !props.disabled
					},
					{
						[cn({
							[props.variants[props.size]]: props.variants[props.size]
						})]: props.variants && props.size
					},
					{
						[cn({
							[props.variants.disabled]: props.variants.disabled
						})]: props.variants && props.disabled
					},
					{
						[cn({
							[props.variants.inGroup]: props.variants.inGroup
						})]: props.variants && isInGroup.value
					},
					{
						[cn({
							[props.variants.disabled]: props.variants.disabled,
							[props.variants[`${props.variant}_disabled`]]: props.variants[`${props.variant}_disabled`]
						})]: props.variants && props.disabled
					},
					{
						[cn({
							[props.variants.active]: props.variants.active,
							[props.variants[`${props.variant}_active`]]: props.variants[`${props.variant}_active`]
					})]: props.variants && isActive.value
					},
					{
						[cn({
							[props.variants.first]: props.variants.first,
							[props.variants[`${props.variant}_first`]]: props.variants[`${props.variant}_first`]
						})]: props.variants && isFirst.value
					},
					{
						[cn({
							[props.variants.middle]: props.variants.middle,
							[props.variants[`${props.variant}_middle`]]: props.variants[`${props.variant}_middle`]
						})]: props.variants && isMiddle.value
					},
					{
						[cn({
							[props.variants.last]: props.variants.last,
							[props.variants[`${props.variant}_last`]]: props.variants[`${props.variant}_last`]
						})]: props.variants && isLast.value
					}
				]}
				disabled={props.disabled}
				onClick={handleClick}
			>
				{slots.default && slots.default()}
			</button>
		)
	},
})
