// vue/src/components/modal/modules/ModalBody/ModalBody.tsx
import { defineComponent, ExtractPublicPropTypes } from "vue"
import cn from 'classnames'
import { definePropType } from "../../../../utils"

import { bodyStyle, bodyIconStyle, bodyIcon, bodyContentStyle, bodyIconSize } from "./stylingProps"
import { Icon } from "../../../icon"

const modalBodyStylingProps = {
  style: bodyStyle,
  iconStyle: bodyIconStyle,
  icon: bodyIcon,
  iconSize: bodyIconSize,
  contentStyle: bodyContentStyle
}

export const modalBodyProps = {
  content: {
    type: definePropType<string>(String),
    default: ''
  },
  ...modalBodyStylingProps
}

export type ModalBodyProps = ExtractPublicPropTypes<typeof modalBodyProps>

export const ModalBody = defineComponent({
  name: 'ModalBody',
  props: modalBodyProps,
  setup(props, { slots }) {
    return () => (
      <div class={cn({[props.style]: props.style})}>
        <div class={cn({[props.iconStyle]: props.iconStyle})}>
          <Icon name={props.icon} size={props.iconSize} />
        </div>
        <div class={cn({[props.contentStyle]: props.contentStyle})}>
          { slots.content ? slots.content() : props.content }
        </div>
      </div>
    )
  }
})

// react/src/components/Modal/modules/ModalBody/ModalBody.tsx
import { FC } from "react";
import { ModalBodyProps } from "./types";
import cn from 'classnames'
import {
  bodyStyle,
  bodyContentStyle,
  bodyIconStyle
} from '@shared/components/modal/modules/body/styles.css'
import { Icon } from "../../../Icon";

export {
  bodyStyle as modalBodyStyle,
  bodyContentStyle as modalBodyContentStyle,
  bodyIconStyle as modalBodyIconStyle
}

export const ModalBody: FC<ModalBodyProps> = ({
  style = bodyStyle,
  iconStyle = bodyIconStyle,
  contentStyle = bodyContentStyle,
  icon = 'ri-information-line',
  iconSize = 'medium',
  children,
  content = ''
}) => (
  <div className={cn({[style]: style})}>
    <div className={cn({[iconStyle]: iconStyle})}>
      <Icon name={icon} size={iconSize} />
    </div>
    <div className={cn({[contentStyle]: contentStyle})}>
      {children ? children : content}
    </div>
  </div>
)
