// react/src/components/Textarea/Textarea.tsx
import { FC, SyntheticEvent, useId } from "react";
import cn from 'classnames'
import { TextareaProps } from "./types";
import {
  textareaFieldBoxStyle,
  textareaFieldBoxVariants,
  textareaLabelStyle,
  textareaLabelVariants,
  textareaPlaceholderStyle,
  textareaPlaceholderVariants,
  textareaStyle as _textareaStyle,
  textareaVariants as _textareaVariants,
  textareaFieldStyle,
  textareaFieldVariants
} from "@shared/components/textarea";
import { useInputStateHandlers } from "../../hooks";

export const Textarea: FC<TextareaProps> = ({
  style = _textareaStyle,
  variants = _textareaVariants,
  labelStyle = textareaLabelStyle,
  labelVariants = textareaLabelVariants,
  fieldBoxStyle = textareaFieldBoxStyle,
  fieldBoxVariants = textareaFieldBoxVariants,
  placeholderStyle = textareaPlaceholderStyle,
  placeholderVariants = textareaPlaceholderVariants,
  textareaStyle = textareaFieldStyle,
  textareaVariants = textareaFieldVariants,
  size = 'medium',
  disabled = false,
  invalid = false,
  id = '',
  value = '',
  onChange = () => {},
  onInput = () => {},
  label = '',
  renderLabel = null,
  children = null,
  placeholder = '',
  renderPlaceholder = null,
  attributes = {}
}) => {
  const usableId = id ? id : useId()

  const {
    hoverState: [hover],
    focusState: [focus],
    handleMouseIn,
    handleMouseOut,
    handleFocus,
    handleBlur
  } = useInputStateHandlers(disabled)
  return <div
    className={cn({
      [style]: style,
      [variants[size]]: variants[size] && size,
      [variants.disabled]: variants.disabled && disabled,
      [variants.invalid]: variants.invalid && invalid,
      [variants.hover]: variants.hover && hover,
      [variants.focus]: variants.focus && focus
    })}
    onMouseEnter={handleMouseIn}
    onMouseLeave={handleMouseOut}
  >
    {renderLabel
      ? typeof renderLabel === 'function'
        ? renderLabel()
        : renderLabel
      : label && (
          <label
            htmlFor={usableId}
            className={cn({
              [labelStyle]: labelStyle,
              [labelVariants[size]]: labelVariants[size] && size,
              [labelVariants.disabled]: labelVariants.disabled && disabled,
              [labelVariants.invalid]: labelVariants.invalid && invalid,
              [labelVariants.hover]: labelVariants.hover && hover,
              [labelVariants.focus]: labelVariants.focus && focus,
              [labelVariants.filled]: labelVariants.filled && value
            })}
          >
            {label}
          </label>
        )
    }
    {children
      ? typeof children === 'function'
        ? children({
            id: usableId,
            hover, focus,
            handleFocus, handleBlur,
            handleMouseIn, handleMouseOut
          })
        : children
      : <div
          className={cn({
            [fieldBoxStyle]: fieldBoxStyle,
            [fieldBoxVariants[size]]: fieldBoxVariants[size] && size,
            [fieldBoxVariants.disabled]: fieldBoxVariants.disabled && disabled,
            [fieldBoxVariants.invalid]: fieldBoxVariants.invalid && invalid,
            [fieldBoxVariants.filled]: fieldBoxVariants.filled && value,
            [fieldBoxVariants.focus]: fieldBoxVariants.focus && focus,
            [fieldBoxVariants.hover]: fieldBoxVariants.hover && hover
          })}
        >
          {renderPlaceholder && (
            <div className={cn({
              [placeholderStyle]: placeholderStyle,
              [placeholderVariants[size]]: placeholderVariants[size] && size,
              [placeholderVariants.disabled]: placeholderVariants.disabled && disabled,
              [placeholderVariants.invalid]: placeholderVariants.invalid && invalid,
              [placeholderVariants.filled]: placeholderVariants.filled && value,
              [placeholderVariants.hover]: placeholderVariants.hover && hover,
              [placeholderVariants.focus]: placeholderVariants.focus && focus
            })}>
              {typeof renderPlaceholder === 'function'
                ? renderPlaceholder()
                : renderPlaceholder
              }
            </div>
          )}
          <textarea
            id={usableId}
            {...attributes}
            className={cn({
              [textareaStyle]: textareaStyle,
              [textareaVariants[size]]: textareaVariants[size] && size,
              [textareaVariants.disabled]: textareaVariants.disabled && disabled,
              [textareaVariants.invalid]: textareaVariants.invalid && invalid,
              [textareaVariants.filled]: textareaVariants.filled && value,
              [textareaVariants.hover]: textareaVariants.hover && hover,
              [textareaVariants.focus]: textareaVariants.focus && focus
            })}
            placeholder={placeholder}
            disabled={disabled}
            value={value}
            onFocus={handleFocus}
            onBlur={handleBlur}
            onChange={(e: SyntheticEvent) => onChange((e.target as HTMLTextAreaElement).value)}
            onInput={(e: SyntheticEvent) => onInput((e.target as HTMLTextAreaElement).value)}
          ></textarea>
        </div>
    }
  </div>
}

// vue/src/components/textarea/Textarea.tsx
import { TextareaEmitters, TextareaSize, TextareaValue } from "@shared/components/textarea/types";
import { definePropType } from "../../utils";
import { computed, defineComponent, ExtractPublicPropTypes, useId } from "vue";
import cn from 'classnames'
import {
  textareaFieldBoxStyle,
  textareaFieldBoxVariants,
  textareaFieldStyle,
  textareaFieldVariants,
  textareaLabelStyle,
  textareaLabelVariants,
  textareaPlaceholderStyle,
  textareaPlaceholderVariants,
  textareaStyle,
  textareaVariants
} from "@shared/components/textarea/styles.css";
import { useInputStateHandlers } from "../../hooks";

export const textareaProps = {
  style: {
    type: String,
    default: textareaStyle
  },
  variants: {
    type: Object,
    default: textareaVariants
  },
  labelStyle: {
    type: String,
    default: textareaLabelStyle
  },
  labelVariants: {
    type: Object,
    default: textareaLabelVariants
  },
  fieldBoxStyle: {
    type: String,
    default: textareaFieldBoxStyle
  },
  fieldBoxVariants: {
    type: Object,
    default: textareaFieldBoxVariants
  },
  textareaStyle: {
    type: String,
    default: textareaFieldStyle
  },
  textareaVariants: {
    type: Object,
    default: textareaFieldVariants
  },
  placeholderStyle: {
    type: String,
    default: textareaPlaceholderStyle
  },
  placeholderVariants: {
    type: Object,
    default: textareaPlaceholderVariants
  },
  id: {
    type: definePropType<string>(String),
    default: ''
  },
  label: {
    type: definePropType<string>(String),
    default: ''
  },
  placeholder: {
    type: definePropType<string>(String),
    default: ''
  },
  value: {
    type: definePropType<TextareaValue>(String),
    default: ''
  },
  disabled: {
    type: definePropType<boolean>(Boolean),
    default: false
  },
  size: {
    type: definePropType<TextareaSize>(String),
    default: 'medium'
  },
  invalid: {
    type: definePropType<boolean>(Boolean),
    default: false
  }
} as const

export type TextareaProps = ExtractPublicPropTypes<typeof textareaProps>

export const textareaEmitters: TextareaEmitters = {
  input: (value: string) => typeof value === 'string',
  change: (value: string) => typeof value === 'string'
}

export const Textarea = defineComponent({
  name: 'Textarea',
  props: textareaProps,
  emits: textareaEmitters,
  setup(props, { slots, attrs, emit }) {
    const id = props.id ? props.id : useId()
    const disabled = computed(() => props.disabled)

    const {
      hover,
      focus,
      handleMouseIn,
      handleMouseOut,
      handleFocus,
      handleBlur
    } = useInputStateHandlers(disabled)

    return () => (
      <div
        class={cn({
          [props.style]: props.style,
          [props.variants[props.size]]: props.variants[props.size] && props.size,
          [props.variants.disabled]: props.variants.disabled && props.disabled,
          [props.variants.invalid]: props.variants.invalid && props.invalid,
          [props.variants.hover]: hover.value,
          [props.variants.focus]: focus.value
        })}
        onMouseenter={handleMouseIn}
        onMouseleave={handleMouseOut}
      >
        {slots.label
          ? slots.label()
          : <label
              for={id}
              class={cn({
                [props.labelStyle]: props.labelStyle,
                [props.labelVariants[props.size]]: props.labelVariants[props.size] && props.size,
                [props.labelVariants.disabled]: props.labelVariants.disabled && props.disabled,
                [props.labelVariants.invalid]: props.labelVariants.invalid && props.invalid,
                [props.labelVariants.hover]: props.labelVariants.hover && hover.value,
                [props.labelVariants.filled]: props.labelVariants.filled && props.value,
                [props.labelVariants.focus]: props.labelVariants.focus && focus.value
              })}
            >
              {props.label}
            </label>
        }
        {slots.default
          ? slots.default({
              id,
              hover,
              focus,
              handleFocus,
              handleBlur
            })
          : <div
              class={cn({
                [props.fieldBoxStyle]: props.fieldBoxStyle,
                [props.fieldBoxVariants[props.size]]: props.fieldBoxVariants[props.size] && props.size,
                [props.fieldBoxVariants.disabled]: props.fieldBoxVariants.disabled && props.disabled,
                [props.fieldBoxVariants.invalid]: props.fieldBoxVariants.invalid && props.invalid,
                [props.fieldBoxVariants.filled]: props.fieldBoxVariants.filled && props.value,
                [props.fieldBoxVariants.hover]: props.fieldBoxVariants.hover && hover.value,
                [props.fieldBoxVariants.focus]: props.fieldBoxVariants.focus && focus.value
              })}
            >
              {slots.placeholder && (
                <div class={cn({
                  [props.placeholderStyle]: props.placeholderStyle,
                  [props.placeholderVariants[props.size]]: props.placeholderVariants[props.size] && props.size,
                  [props.placeholderVariants.disabled]: props.placeholderVariants.disabled && props.disabled,
                  [props.placeholderVariants.invalid]: props.placeholderVariants.invalid && props.invalid,
                  [props.placeholderVariants.filled]: props.placeholderVariants.filled && props.value,
                  [props.placeholderVariants.hover]: props.placeholderVariants.hover && hover.value,
                  [props.placeholderVariants.focus]: props.placeholderVariants.focus && focus.value
                })}>
                  {slots.placeholder()}
                </div>
              )}
              <textarea
                id={id}
                {...attrs}
                class={cn({
                  [props.textareaStyle]: props.textareaStyle,
                  [props.textareaVariants[props.size]]: props.textareaVariants[props.size] && props.size,
                  [props.textareaVariants.disabled]: props.textareaVariants.disabled && props.disabled,
                  [props.textareaVariants.invalid]: props.textareaVariants.invalid && props.invalid,
                  [props.textareaVariants.filled]: props.textareaVariants.filled && props.value,
                  [props.textareaVariants.hover]: props.textareaVariants.hover && hover.value,
                  [props.textareaVariants.focus]: props.textareaVariants.focus && focus.value
                })}
                placeholder={props.placeholder}
                disabled={props.disabled}
                value={props.value}
                onFocus={handleFocus}
                onBlur={handleBlur}
                onChange={(e: Event) => emit('change', (e.target as HTMLInputElement).value)}
                onInput={(e: Event) => emit('input', (e.target as HTMLInputElement).value)}
              ></textarea>
            </div>
        }
      </div>
    )
  }
})
